language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - nightly
  - hhvm
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    
branches:
  only:
    - developer
   
services:
  - mysql
  
mysql:
  database: yetiforce
  username: root
  encoding: utf8
  
before_script:
- composer install
- sudo wget https://phar.phpunit.de/phpunit.phar
- sudo chmod +x phpunit.phar
- sudo mv phpunit.phar /usr/local/bin/phpunit
- phpunit --version
- sudo wget https://scrutinizer-ci.com/ocular.phar
- sudo chmod +x ocular.phar
- sudo mv ocular.phar /usr/local/bin/ocular
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'"
- mysql -e "create database IF NOT EXISTS yetiforce;" -uroot
- cp tests/config.inc.txt config/config.inc.php
- cp tests/debug.txt config/debug.php
- cp tests/developer.txt config/developer.php
- cp tests/.htaccess .htaccess
  
script:
- cd tests
- phpunit --debug --verbose --coverage-text --coverage-clover=coverage.clover
    
after_script:
- cd ..
- cat tests/LoginPage.txt
- cat tests/DetailView.txt
- cat tests/ListView.txt
- cat tests/EditView.txt
- cat tests/records.log
- cat cache/logs/phpError.log
- cat cache/logs/system.log
- cat cache/logs/Importer.log
- php ocular code-coverage:upload --format=php-clover coverage.clover
- bash <(curl -s https://codecov.io/bash) 
