sudo: required

dist: trusty
  
language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    - php: 7.2
    
branches:
  only:
    - developer
   
services:
  - mysql
  
mysql:
  database: yetiforce
  username: root
  encoding: utf8
  
before_script:
- |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
        sudo wget https://phar.phpunit.de/phpunit-5.7.phar
        sudo chmod +x phpunit-5.7.phar
        sudo mv phpunit-5.7.phar /usr/local/bin/phpunit
    else
        sudo wget https://phar.phpunit.de/phpunit-6.2.phar
        sudo chmod +x phpunit-6.2.phar
        sudo mv phpunit-6.2.phar /usr/local/bin/phpunit
    fi
- sudo chmod -R 777 tests/setup/
- ./tests/setup/before_script.sh
- ./tests/setup/apache.sh
- ./tests/setup/selenium.sh
  
script:
- cd tests
- /usr/local/bin/phpunit --debug --verbose --coverage-text --coverage-clover=coverage.xml
    
after_script:
- sudo cat /var/log/apache2/error.log
- sudo cat /var/log/apache2/access.log
- sudo cat /var/log/apache2/other_vhosts_access.log
- cat ../tests/records.log
- cat ../cache/logs/errors.log
- cat ../cache/logs/request.log
- cat ../cache/logs/phpError.log
- cat ../cache/logs/system.log
- cat ../cache/logs/Importer.log
- php ocular code-coverage:upload --format=php-clover coverage.xml
- bash <(curl -s https://codecov.io/bash) 
