language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - nightly
  - hhvm
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    
services:
  - mysql
  
mysql:
  database: yetiforce
  username: root
  encoding: utf8
  
before_script:
- if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-add tests/travis.php.ini; fi
- if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat tests/travis.php.ini >> /etc/hhvm/php.ini; fi
- sudo wget https://phar.phpunit.de/phpunit.phar
- sudo chmod +x phpunit.phar
- sudo mv phpunit.phar /usr/local/bin/phpunit
- phpunit --version
- sudo wget https://scrutinizer-ci.com/ocular.phar
- sudo chmod +x ocular.phar
- sudo mv ocular.phar /usr/local/bin/ocular
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'"
- mysql -e "create database IF NOT EXISTS yetiforce;" -uroot
- cp tests/config.inc.txt config/config.inc.php
- cp tests/debug.txt config/debug.php
- cp tests/developer.txt config/developer.php
- cp tests/.htaccess .htaccess
  
script:
- cd tests
- phpunit --debug --verbose --coverage-text --coverage-clover=coverage.clover
    
after_script:
- cat cache/logs/phpError.log
- cat LoginPage.txt
- cat DetailView.txt
- cat ListView.txt
- cat EditView.txt
- cat cache/logs/Importer.log
- php ocular code-coverage:upload --format=php-clover coverage.clover
- bash <(curl -s https://codecov.io/bash) 

branches:
  only:
    - developer
